version: '3'
services:
  api-service:
    container_name: pipeline
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run start:dev api-service
    env_file:
      - ./.env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 9001:9001
