services:
  api-service:
    build:
      context: .
      dockerfile: ./apps/api-service/Dockerfile
      target: development
    command: npm run start:dev api-service
    env_file:
      - ./.env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 9001:9001
