name: Push-to-EC2

# Trigger deployment only on push to master branch
on:
  push:
    branches: [main, workflow_dispatch]
env:
#  bucket_name: "<example-bucket-name>"
    AWS_REGION: ap-south-1
    REMOTE_HOST: 13.126.152.69
    REMOTE_USER: ec2-user
    TARGET_DIR: /home/ubuntu/cicddemo
        

jobs:
  deploy:
    name: Deploy to EC2 on master branch push
    runs-on: self-hosted

    steps:
      - name: Checkout the files
        uses: actions/checkout@v3
      - name: build docker image
        run : sudo docker-compose -f docker-compose.yml up -d --build

  