name: Push-to-EC2

# Trigger deployment only on push to master branch
on:
  push:
    branches: [main, workflow_dispatch]
jobs:
  deploy:
    name: Deploy to EC2 on master branch push
    runs-on: self-hosted

    steps:
      - name: Checkout the files
        uses: actions/checkout@v3
      - name: build docker image
        run : sudo docker-compose -f docker-compose.yml up -d --build

  